on:
  pull_request:
    branches: [master, dev]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: lintr

      - name: Lint files 
        run:  |
          R -e 'write_rds(lint("main.R", cache  = T), "lints/lint_main.Rds")'
          R -e 'write_rds(lint("donwload_data.R", cache  = T), "lints/download_data.Rds")'
          
      - name: commit lint suggestions
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add lints/\*.R
          git commit -m 'lint files' || echo "No lints to commit"
          git push origin master|| echo "No lints to commit"
