#  Controls when the action will run.
#  “At 20:00 on Saturday.”
#  https://crontab.guru/
#  On push for testin purpose
on:
  schedule:
    - cron:  '0 13 * * SAT'

name: update-data

jobs: 
  update-data:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    
    - uses: r-lib/actions/setup-r@master
      with:
          use-public-rspm: true

    - name: Install packages from renv
      run:  |
        R -e 'install.packages("renv")'
        R -e 'library(renv)'
        R -e 'restore()'
        
        
    - name: Download data from source
      run: Rscript dowload_data.R
        
# Run pipeline
    - name: Scrape and Clean and Write
      run: Rscript main.R
      