#  Controls when the action will run.
#  “At 20:00 on Saturday.”
#  https://crontab.guru/
#  On push for testin purpose
on:
  push:
    branches: master
  # schedule:
  #   - cron:  '0 13 * * SAT'

name: update-data

jobs: 
  update-data:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
      
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-renv@v1
      with:
        cache-version: 2
        
    - name: Download data from source
      run: Rscript dowload_data.R
        
    - name: Group and Pin
      run: Rscript main.R
      