#  Controls when the action will run.
#  “At 20:00 on Saturday.”
#  https://crontab.guru/
#  On push for testin purpose
on:
  schedule:
    - cron:  '0 13 * * SAT'

name: update-data

jobs: 
  update-data:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/Library/Application Support/renv
    
      
    steps:
    
    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
          
    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()
    
# - uses: actions/checkout@master
# - uses: r-lib/actions/setup-r@master
        
    - name: Download data from source
      run: Rscript dowload_data.R
        
# Run pipeline
    - name: Group and Pin
      run: Rscript main.R
      